---
# Default values: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
argo-cd:
  global:
    image:
      repository: alinbalutoiu/argocd
  server:
    ingress:
      enabled: false
      ingressClassName: nginx

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS

      hosts:
        - argocd.chapusot.fr
      tls:
        - hosts:
            - argocd.chapusot.fr
          secretName: argocd-cert
