apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: component-config/argocd/
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: component-config/argocd
    repoURL: git@github.com:ChapChap/ChapoCluster-argo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
